#pragma once

#ifndef _DRMS_ENUMERATIONS_H
#define _DRMS_ENUMERATIONS_H

namespace DRMS {
	enum class DRMSCommandType {
		DRMS_COMMAND_TYPE_END_SESSION,

		DRMS_COMMAND_TYPE_REQUEST_FORM,
		DRMS_COMMAND_TYPE_SUBMIT_FORM,
		DRMS_COMMAND_TYPE_RESOURCE_CHECK,
		DRMS_COMMAND_TYPE_REQUEST_CANCELATION,

		DRMS_COMMAND_TYPE_FOLDER_HIERARCHY,

		DRMS_COMMAND_TYPE_VERIFICATION,

		DRMS_COMMAND_TYPE_PUSH,
		DRMS_COMMAND_TYPE_BUILD_SOLUTION,
		DRMS_COMMAND_TYPE_EXECUTE,
		DRMS_COMMAND_TYPE_REGISTER,

		DRMS_COMMAND_TYPE_UNKNOWN
	};

	enum class DRMSCommandSubType {
		DRMS_COMMAND_SUB_TYPE_CREATION_FORM,
		DRMS_COMMAND_SUB_TYPE_UPDATION_FORM,
		DRMS_COMMAND_SUB_TYPE_DELETION_FORM,

		DRMS_COMMAND_SUB_TYPE_CREATE_CHECK,
		DRMS_COMMAND_SUB_TYPE_AVAILABLE_CHECK,
		DRMS_COMMAND_SUB_TYPE_DELETE_CHECK,

		DRMS_COMMAND_SUB_TYPE_UNKNOWN
	};

	enum DRMSCommandHierarchy {
		DRMS_COMMAND_PRIMARY = 0,
		DRMS_COMMAND_SECONDARY = 1,
		DRMS_COMMAND_TERNARY = 2,
	};
}

#endif // !_DRMS_ENUMERATIONS_H
